# Generated by Django 4.0.3 on 2022-03-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=30, verbose_name='Soyisim')),
                ('mail', models.EmailField(max_length=50, verbose_name='Mail')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='title',
            new_name='ilac_adi',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='author',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='content',
        ),
        migrations.AddField(
            model_name='medicine',
            name='ilacfiyati',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prospekt',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Recete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('hasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.patient')),
                ('tags', models.ManyToManyField(to='medicine.medicine')),
            ],
        ),
    ]
