# Generated by Django 4.0.3 on 2022-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_patient_rename_title_medicine_ilac_adi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recete',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ilacfiyati',
            field=models.FloatField(null=True, verbose_name='İlaç Fiyatı'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='prospekt',
            field=models.TextField(max_length=200, null=True, verbose_name='Prospektüs'),
        ),
        migrations.AlterField(
            model_name='recete',
            name='tags',
            field=models.ManyToManyField(to='medicine.medicine', verbose_name='İlaçlar'),
        ),
    ]
