# Generated by Django 4.0.3 on 2022-04-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_recete_totalfiyat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recete',
            name='totalfiyat',
        ),
    ]
