# Generated by Django 4.0.3 on 2022-04-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_remove_recete_totalfiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='recete',
            name='totalfiyat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
