# Generated by Django 4.0.3 on 2022-04-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_alter_recete_totalfiyat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recete',
            name='totalfiyat',
        ),
    ]
