# Generated by Django 4.0.3 on 2022-04-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_remove_recete_totalfiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='recete',
            name='toplam',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
